encryption_key = "kpxQmf1IuVBp9UPQQPsGZ5iXN0jE2ewZ"
jwt_secret = "your-jwt-secret-key"

[supabase]
url = "https://cjsbrplczdmeifwvrhza.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNqc2JycGxjemRtZWlmd3ZyaHphIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTAwOTEsImV4cCI6MjA1NDc4NjA5MX0.kgB7mew35H1_Y_gTcEsIMDh_jnszmtzCnOyT0rbFZBI"